"""Test

Revision ID: 81cfd7b81c12
Revises: c2d530aa52da
Create Date: 2025-08-24 17:04:28.412780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cfd7b81c12'
down_revision: Union[str, Sequence[str], None] = 'c2d530aa52da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('topic', sa.Text(), nullable=True))
    op.add_column('school_newsletters', sa.Column('max_emails', sa.Integer(), nullable=True))
    op.add_column('school_newsletters', sa.Column('first_pass_complete', sa.Boolean(), nullable=True))
    op.add_column('school_newsletters', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_newsletters', 'completed_at')
    op.drop_column('school_newsletters', 'first_pass_complete')
    op.drop_column('school_newsletters', 'max_emails')
    op.drop_column('emails', 'topic')
    # ### end Alembic commands ###
