"""“V1.0.1”

Revision ID: c3fd2a22f464
Revises: 81cfd7b81c12
Create Date: 2025-08-31 16:41:37.805305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fd2a22f464'
down_revision: Union[str, Sequence[str], None] = '81cfd7b81c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_index(op.f('idx_emails_due'), table_name='emails', postgresql_where='(sent = false)')
    op.drop_index(op.f('idx_emails_plan_sent_pos'), table_name='emails')
    op.create_index(op.f('ix_emails_status'), 'emails', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_status'), table_name='emails')
    op.create_index(op.f('idx_emails_plan_sent_pos'), 'emails', ['plan_id', 'sent', 'position_in_plan'], unique=False)
    op.create_index(op.f('idx_emails_due'), 'emails', ['send_date'], unique=False, postgresql_where='(sent = false)')
    op.drop_column('emails', 'status')
    # ### end Alembic commands ###
